name: Deploy

on:
  workflow_run:
    workflows: ["Test"]
    branches: main
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest

    steps:
      - name: SSH
        uses: appleboy/ssh-action@master
        with:
          host: 5.78.89.29
          username: ${{ vars.USERNAME}}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd tickr-server
            docker compose down
            docker compose up --build -d
            docker image prune -a
