name: Deploy

on:
  workflow_run:
    workflows: ["Test"]
    branches: main
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest

    steps:
      - name: SSH
        uses: appleboy/ssh-action@master
        with:
          host: 2a01:4ff:1f0:8a4a::1
          username: ${{ vars.USERNAME}}
          key: ${{ secrets.PRIVATE_KEY }}
          protocol: tcp6
          port: 22
          debug: true
          script: |
            touch here.md
